# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: default

stages:
- stage: test
  jobs:
    - job: manual-approve
      displayName: manual_approve
      steps:
      - task: ManualValidation@0
        inputs:
          notifyUsers: 'ggjjrrw@sina.com'
    - job: after_test
      displayName: do after test
      container: maven:3.8.6-jdk-11
      steps:
      - script: echo "after test1"
      - script: exit 1
      - script: echo "after test2"
    - job: maven_test
      displayName: do maven test
      container: maven:3.8.6-jdk-11
      steps:
      - script: echo "maven test"
    - job: condition_test
      displayName: condition test
      dependsOn: maven_test
- stage: build
  jobs:
  - job: maven_build
    displayName: do maven build
    container: maven:3.8.6-jdk-11
    steps:
    - script: mvn clean package